<?xml version="1.0"?>
<robot name="hakuroukun" xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <!-- Import all robot parts which were xacroed -->
    <xacro:include filename="$(find hakuroukun_description)/urdf/hakuroukun_inertia_box.xacro" />
    <!-- Import Rviz colors -->
    <xacro:include filename="$(find hakuroukun_description)/urdf/colors.xacro" />
    <!-- Import robot properties -->
    <xacro:include filename="$(find hakuroukun_description)/urdf/properties.xacro" />
    <!-- Import wheels and actuator properties -->
    <xacro:include filename="$(find hakuroukun_description)/urdf/actuators_wheels.xacro" />
    <!-- Import sensors -->
    <xacro:include filename="$(find hakuroukun_description)/urdf/sensors.xacro" />

    <xacro:property name="robot_namespace" value="hakuroukun"/>

    <!-- Base link-->
    <link name="base_link"> 
        <visual>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </visual>
        
        <collision>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <!-- rear center-->
    <link name="rear_axis_center">
        <visual>
        <geometry>
            <box size="0.01 0.01 0.01"/>
        </geometry>
        <material name="Red"/>
        </visual>
    </link>
    <gazebo reference="rear_axis_center">
        <material>Gazebo/Red</material>
    </gazebo>
    <joint name="base_link_to_rear_axis_center" type="fixed">
        <parent link="base_link" />
        <child link="rear_axis_center" />
        <origin xyz="0.0 0.0 ${radius}" />
    </joint>

    <!-- Robot Frame-->
    <link name="robot_frame">
        <visual>
            <geometry>  
                <mesh filename="package://hakuroukun_description/meshes/new_base_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <material name="Green"/>
        </visual>
        
        <collision>
            <geometry>
                <mesh filename="package://hakuroukun_description/meshes/new_base_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        
        <xacro:inertial_box mass="${robot_mass}" x="${robot_length}" y="${robot_width}" z="${robot_height}" />

    </link>

    <gazebo reference="robot_frame">
        <material>Gazebo/Green</material>
    </gazebo>

    <joint name="base_link_to_robot_frame" type="fixed">
        <parent link="rear_axis_center" />
        <child link="robot_frame" />
        <origin xyz="${base_link_to_robot_frame_X} ${base_link_to_robot_frame_Y} ${base_link_to_robot_frame_Z}" />
    </joint>

    <!-- lidar center-->
    <link name="lidar_center">
        <visual>
        <geometry>
            <box size="0.01 0.01 0.01"/>
        </geometry>
        <material name="Red"/>
        </visual>
    </link>
    <gazebo reference="lidar_center">
        <material>Gazebo/Red</material>
    </gazebo>
    <joint name="rear_axis_center_to_lidar_center" type="fixed">
        <parent link="rear_axis_center" />
        <child link="lidar_center" />
        <origin xyz="1.03 0.0 ${0.365-rear_radius}" />
    </joint>

<!-- ///////////////////////////////////////// STEERING //////////////////////////////////// -->
    <xacro:steering_continuous name="front_wheel_shaft" 
        parent_link="rear_axis_center" 
        mass="${mass_steering_unit}"
        size_x="${steering_X}"  size_y="${steering_Y}" size_z="${steering_Z}"
        x="${rear_axis_center_to_steering_center}" y="-0.01" z="-0.02"
        file_name="package://hakuroukun_description/meshes/steering.stl" />

<!-- ///////////////////////////////////////// WHEELS //////////////////////////////////// -->

    <xacro:wheel_front name="front_wheel" 
        parent_link="front_wheel_shaft" 
        mass="${mass_wheel}" 
        radius="${radius}"
        thickness="${thickness}" 
        x="0.0" y="0.0" z="0.0" 
        mu1="0.7" mu2="0.7" 
        kp="10000000" kd="40"
        file_name="package://hakuroukun_description/meshes/front_wheel.stl" />

    <xacro:axis_and_wheel name="rear_wheel" 
        parent_link="rear_axis_center" 
        mass="${rear_mass_wheel}" 
        radius="${rear_radius}"
        thickness="${rear_thickness}" 
        x="0.0" y="0.0" z="-0.02" 
        mu1="0.7" mu2="0.7" 
        kp="10000000" kd="40"
        file_name="package://hakuroukun_description/meshes/new_rear.stl" />

    <xacro:imu_sensor parent="rear_axis_center" imu_name="imu" imu_topic="imu/data_raw" mass="${imu_mass}" sizex="0.03" sizey="0.03" sizez="0.005" ox="0.62" oy="-0.25" oz="${1.00-rear_radius}" update_rate="${imu_update_rate}" noise="${imu_noise}" />

    <xacro:gps_sensor parent="rear_axis_center" gps_name="gps" gps_topic="fix" mass="${gps_mass}" sizex="0.03" sizey="0.03" sizez="0.005" ox="0.6" oy="0.0" oz="${1.365-rear_radius}" update_rate="${gps_update_rate}" initial_latitude="${gps_latitude}" initial_longitude="${gps_longitude}" noise="${gps_noise}" />

    <xacro:lidar_sensor parent="rear_axis_center" lidar_name="right_lidar" length="${lidar_length}" radius="${lidar_radius}" mass="${lidar_mass}" ox="1.03" oy="-0.31" oz="${0.365-rear_radius+0.05}" roll="0" pitch="0" yaw="${pi}" update_rate="${lidar_update_rate}" min_angle="${lidar_min_angle}" max_angle="${lidar_max_angle}" min_range="${lidar_min_range}" max_range="${lidar_max_range}" range_resolution="${lidar_range_resolution}" stdv="${lidar_stdv}" />

    <xacro:lidar_sensor parent="rear_axis_center" lidar_name="left_lidar" length="${lidar_length}" radius="${lidar_radius}" mass="${lidar_mass}" ox="1.03" oy="0.31" oz="${0.365-rear_radius+0.05}" roll="0" pitch="0" yaw="${pi}" update_rate="${lidar_update_rate}" min_angle="${lidar_min_angle}" max_angle="${lidar_max_angle}" min_range="${lidar_min_range}" max_range="${lidar_max_range}" range_resolution="${lidar_range_resolution}" stdv="${lidar_stdv}" />

    <xacro:ground_truth parent="base_link" sizex="0.01" sizey="0.01" sizez="0.01" ox="0.0" oy="0.0" oz="0.01" mass="1"/>

    <xacro:zed2_camera camera_name="camera_link" parent="rear_axis_center" mass="0.06" ox="1.01" oy="0.0" oz="${1.195-rear_radius}" roll="0" pitch="0" yaw="0" />

    <!-- ////////////////////////////// GAZEBO ROS PLUGIN //////////////////////////////////// -->

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>

</robot>
