#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from hakuroukun_control.hakuroukun_control_node import HakuroukunControlNode

try:
    hakuroukun_control_node = HakuroukunControlNode()
    hakuroukun_control_node.run()
except rospy.ROSInterruptException:
    pass
