version: '3'

services:
  ros-master:
    image: ros:noetic-ros-core
    container_name: ros-master
    command: stdbuf -o L roscore
    network_mode: host
    
  hakuroukun-robot:
    user: root
    # depends_on: 
    #   - ros-master
    image: hakuroukun_robot:windows
    build:
      context: ..
      dockerfile: ./hakuroukun_dockerfiles/Dockerfile.windows
    container_name: hakuroukun-robot
    volumes:
      - "../:/root/catkin_ws/src/"
    environment:
      - "GAZEBO_MODEL_PATH=/root/catkin_ws/src/hakuroukun_launch/models/:$GAZEBO_MODEL_PATH"
    privileged: True
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    tty: True
    stdin_open: True
    command: bash

  # robot_communication:
  #   user: root
  #   depends_on: 
  #     - ros-master
  #   image: beaverbot:melodic
  #   build:
  #     context: ..
  #     dockerfile: ./beaverbot_dockerfiles/Dockerfile.melodic
  #   container_name: beaverbot_communication
  #   privileged: True
  #   network_mode: host
  #   tty: True
  #   stdin_open: True
  #   command: bash